#!/bin/bash

# Load color utility functions
if [[ -f "/etc/SSHPlus/colors" ]]; then
    source /etc/SSHPlus/colors
elif [[ -f "/bin/colors" ]]; then
    source /bin/colors
elif [[ -f "$(dirname "$0")/colors" ]]; then
    source "$(dirname "$0")/colors"
fi

tput setaf 7
tput setab 4
tput bold
printf '%33s%s%-12s\n' "Change expiration date"
tput sgr0
echo ""
color_echo " LIST OF USERS AND EXPIRY DATE:" "yellow"
echo ""
tput setaf 7 ; tput bold 
database="/root/users.db"
list_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
i=0
i=0
unset _userPass
while read user; do
	i=$(expr $i + 1)
	_oP=$i
	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
	expire="$(chage -l $user | grep -E "Account expires" | cut -d ' ' -f3-)"
	if [[ $expire == "never" ]]
	then
		# Use color codes for "never" case
		red_code=$(get_color_code "red")
		cyan_code=$(get_color_code "cyan")
		white_code=$(get_color_code "white")
		green_code=$(get_color_code "green")
		yellow_code=$(get_color_code "yellow")
		reset_code=$(get_reset_code)
		echo -e "${red_code}[${cyan_code}$i${red_code}] ${white_code}- ${green_code}$user     ${yellow_code}00/00/0000   S/DATE${reset_code}"
	else
		databr="$(date -d "$expire" +"%Y%m%d")"
		hoje="$(date -d today +"%Y%m%d")"
		if [ $hoje -ge $databr ]
		then
			# Use color codes for expired users
			red_code=$(get_color_code "red")
			cyan_code=$(get_color_code "cyan")
			white_code=$(get_color_code "white")
			green_code=$(get_color_code "green")
			reset_code=$(get_reset_code)
			_user="${red_code}[${cyan_code}$i${red_code}] ${white_code}- ${green_code}$user${white_code}"
			datanormal="${red_code}$(date -d"$expire" '+%d/%m/%Y')${reset_code}"
			expired="${red_code}WON${reset_code}"
			printf '%-62s%-20s%s\n' "$_user" "$datanormal" "$expired"
			echo "exp" > /tmp/exp
		else
			# Use color codes for valid users
			red_code=$(get_color_code "red")
			cyan_code=$(get_color_code "cyan")
			white_code=$(get_color_code "white")
			green_code=$(get_color_code "green")
			yellow_code=$(get_color_code "yellow")
			reset_code=$(get_reset_code)
			_user="${red_code}[${cyan_code}$i${red_code}] ${white_code}- ${green_code}$user${white_code}"
			datanormal="${yellow_code}$(date -d"$expire" '+%d/%m/%Y')${reset_code}"
			ative="${green_code}VALID${reset_code}"
			printf '%-62s%-20s%s\n' "$_user" "$datanormal" "$ative"
		fi
	fi
	_userPass+="\n${_oP}:${user}"
done <<< "${list_user}"
tput sgr0
echo ""
if [ -a /tmp/exp ]
then
	rm /tmp/exp
fi
num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
# Use color functions for prompt
color_echo_n "Type or select a user " "green"
color_echo_n "[" "yellow"
color_echo_n "1" "cyan"
color_echo_n "-" "yellow"
color_echo_n "$num_user" "cyan"
color_echo_n "]" "yellow"
color_echo_n ": " "white"
read -r option
if [[ -z $option ]]
then
	echo ""
	error_msg "Error, Username empty or invalid!"
	exit 1
fi
usuario=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
if [[ -z $usuario ]]
then
	echo ""
	error_msg "Error, Username empty or invalid!!!"
	echo ""
	exit 1
else
	if [[ `grep -c /$usuario: /etc/passwd` -ne 0 ]]
	then
	    echo ""
	    # Use color functions for example text
	    color_echo_n "EX:" "red"
	    color_echo_n "(" "yellow"
	    color_echo_n "DATE: " "green"
	    color_echo_n "DAY/MONTH/YEAR " "white"
	    color_echo_n "OR " "yellow"
	    color_echo_n "DAYS: " "green"
	    color_echo_n "30" "white"
	    color_echo ")" "yellow"
	    echo ""
	    color_echo_n "New date or days for the user " "green"
	    color_echo_n "$usuario: " "yellow"
	    color_echo_n "" "white"
	    read -r inputdate
	    if [[ "$(echo -e "$inputdate" | grep -c "/")" = "0" ]]; then 
	    	udata=$(date "+%d/%m/%Y" -d "+$inputdate days")
	    	sysdate="$(echo "$udata" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
	    else
	    	udata=$(echo -e "$inputdate")
	    	sysdate="$(echo "$inputdate" | awk -v FS=/ -v OFS=- '{print $3,$2,$1}')"
	    fi
		if (date "+%Y-%m-%d" -d "$sysdate" > /dev/null  2>&1)
		then
			if [[ -z $inputdate ]]
			then
				echo ""
				error_msg "You entered an invalid or non-existent date!"
				echo "Enter a valid date in DAY/MONTH/YEAR format"
				echo "For example: 21/04/2021"
				echo ""
				exit 1	
			else
				if (echo $inputdate | egrep [^a-zA-Z] &> /dev/null)
				then
					today="$(date -d today +"%Y%m%d")"
					timemachine="$(date -d "$sysdate" +"%Y%m%d")"
					if [ $today -ge $timemachine ]
					then
						echo ""
						error_msg "You entered a past date or the current day!"
						echo "Enter a future and valid date in DAY/MONTH/YEAR format"
						echo "For example: 21/04/2021"
						echo ""
						exit 1
					else
						chage -E $sysdate $usuario
						echo ""
						success_msg "User Success $usuario new date: $udata"
						echo ""
						exit 1
					fi
				else
					echo ""
					error_msg "You entered an invalid or non-existent date!"
					echo "Enter a valid date in DAY/MONTH/YEAR format"
					echo "For example: 21/04/2021"
					echo ""
					exit 1
				fi
			fi
		else
			echo ""
			error_msg "You entered an invalid or non-existent date!"
			echo "Enter a valid date in DAY/MONTH/YEAR format"
			echo "For example: 21/04/2021"
			echo ""
			exit 1
		fi
	else
		echo ""
		error_msg "The user $usuario does not exist!"
		echo ""
		exit 1
	fi
fi