#!/bin/bash

# Load color utility functions
if [[ -f "/etc/SSHPlus/colors" ]]; then
    source /etc/SSHPlus/colors
elif [[ -f "/bin/colors" ]]; then
    source /bin/colors
elif [[ -f "$(dirname "$0")/colors" ]]; then
    source "$(dirname "$0")/colors"
fi

remove_ovp () {
if [[ -e /etc/debian_version ]]; then
	GROUPNAME=nogroup
fi
user="$1"
cd /etc/openvpn/easy-rsa/
./easyrsa --batch revoke $user
./easyrsa gen-crl
rm -rf pki/reqs/$user.req
rm -rf pki/private/$user.key
rm -rf pki/issued/$user.crt
rm -rf /etc/openvpn/crl.pem
cp /etc/openvpn/easy-rsa/pki/crl.pem /etc/openvpn/crl.pem
chown nobody:$GROUPNAME /etc/openvpn/crl.pem
[[ -e $HOME/$user.ovpn ]] && rm $HOME/$user.ovpn > /dev/null 2>&1
[[ -e /var/www/html/openvpn/$user.zip ]] && rm /var/www/html/openvpn/$user.zip > /dev/null 2>&1
} > /dev/null 2>&1
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/ > /dev/null 2>&1
database="/root/users.db"
clear
tput setaf 7
tput setab 4
tput bold
printf '%32s%s%-13s\n' "Remove SSH User"
tput sgr0
echo ""
# Use menu_option function for menu items
menu_option "1" "REMOVE A USER" "red" "yellow"
menu_option "2" "REMOVE ALL USERS" "red" "yellow"
menu_option "3" "BACK" "red" "yellow"
echo ""
# Use color functions for prompt
color_echo_n "PLEASE SELECT FROM OPTIONS" "green"
color_echo_n " ?" "red"
color_echo_n " : " "white"
read -r -e -i 1 resp
if [[ "$resp" = "1" ]]; then
clear
tput setaf 7
tput setab 4
tput bold
printf '%32s%s%-13s\n' "Remove SSH User"
tput sgr0
echo ""
color_echo "LIST OF USERS:" "yellow"
echo ""
_userT=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody)
i=0
unset _userPass
while read _user; do
	i=$(expr $i + 1)
	_oP=$i
	[[ $i == [1-9] ]] && i=0$i && oP+=" 0$i"
	# Use color codes for user list
	red_code=$(get_color_code "red")
	cyan_code=$(get_color_code "cyan")
	white_code=$(get_color_code "white")
	green_code=$(get_color_code "green")
	reset_code=$(get_reset_code)
	echo -e "${red_code}[${cyan_code}$i${red_code}] ${white_code}- ${green_code}$_user${reset_code}"
	_userPass+="\n${_oP}:${_user}"
done <<< "${_userT}"
echo ""
num_user=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
# Use color functions for prompt
color_echo_n "Type or select a user " "green"
color_echo_n "[" "yellow"
color_echo_n "1" "cyan"
color_echo_n "-" "red"
color_echo_n "$num_user" "cyan"
color_echo_n "]" "yellow"
color_echo_n ": " "white"
read -r option
user=$(echo -e "${_userPass}" | grep -E "\b$option\b" | cut -d: -f2)
if [[ -z $option ]]; then
	echo ""
	error_msg "  Empty or invalid user!   "
	echo ""
	exit 1
elif [[ -z $user ]]; then
	echo ""
	error_msg " Empty or invalid user! "
	echo ""
	exit 1
else
	if cat /etc/passwd |grep -w $user > /dev/null; then
		echo ""
		pkill -f "$user" > /dev/null 2>&1
		deluser --force $user > /dev/null 2>&1
		success_msg " User $user removed successfully! "
		grep -v ^$user[[:space:]] /root/users.db > /tmp/ph ; cat /tmp/ph > /root/users.db
		rm /etc/SSHPlus/senha/$user 1>/dev/null 2>/dev/null
		if [[ -e /etc/openvpn/server.conf ]]; then
			remove_ovp $user
		fi
		exit 1
	elif [[ "$(cat "$database"| grep -w $user| wc -l)" -ne "0" ]]; then
		ps x | grep $user | grep -v grep | grep -v pt > /tmp/rem
		if [[ `grep -c $user /tmp/rem` -eq 0 ]]; then
			deluser --force $user > /dev/null 2>&1
			echo ""
			success_msg " User $user removed successfully! "
			grep -v ^$user[[:space:]] /root/users.db > /tmp/ph ; cat /tmp/ph > /root/users.db
			rm /etc/SSHPlus/senha/$user 1>/dev/null 2>/dev/null
			if [[ -e /etc/openvpn/server.conf ]]; then
				remove_ovp $user
		    fi
			exit 1
		else
		    echo ""
			info_msg "User logged in. Disconnecting..."
			pkill -f "$user" > /dev/null 2>&1
			deluser --force $user > /dev/null 2>&1
			success_msg " User $user successfully removed! "
			grep -v ^$user[[:space:]] /root/users.db > /tmp/ph ; cat /tmp/ph > /root/users.db
			rm /etc/SSHPlus/senha/$user 1>/dev/null 2>/dev/null
			if [[ -e /etc/openvpn/server.conf ]]; then
				remove_ovp $user
		    fi
			exit 1
		fi
	else
		echo ""
		error_msg "The user $user does not exist!"
		echo ""
	fi
fi
elif [[ "$resp" = "2" ]]; then
	clear
	tput setaf 7
	tput setab 4
	tput bold
	printf '%32s%s%-13s\n' "Remove SSH User"
	tput sgr0
	echo ""
	color_echo_n "DO YOU REALLY WANT TO REMOVE ALL USERS? " "yellow"
	color_echo_n "[y/n]: " "white"
	read -r opc	
	if [[ "$opc" = "y" ]]; then
		echo ""
		color_echo_n "Wait" "yellow"
		color_echo_n "." "green"
		color_echo_n "." "red"
		color_echo "." "yellow"
		for user in $(cat /etc/passwd |awk -F : '$3 > 900 {print $1}' |grep -vi "nobody"); do
			pkill -f $user > /dev/null 2>&1
			deluser --force $user > /dev/null 2>&1
        if [[ -e /etc/openvpn/server.conf ]]; then
		   remove_ovp $user
		fi
		done
		rm $HOME/users.db && touch $HOME/users.db
        rm *.zip > /dev/null 2>&1
		echo ""
		success_msg "SUCCESSFULLY REMOVED USERS!"
		sleep 2
		menu
	else
		echo ""
		error_msg "Returning to the menu..."
		sleep 2
		menu
	fi
elif [[ "$resp" = "3" ]]; then
	menu
else
	echo ""
	error_msg "Invalid option !"
	sleep 1.5s
	menu
fi